import { Suspense } from 'react';
import Footer from './Footer/Footer';
import ScrollUp from './componet/ScrollUp/ScrollUp';
import './globals.css';
import { Inter } from 'next/font/google';
import StoreProvide from './Redux/storeProvide';
import Loadingcompante from './loading';
import FacebookPixel from './FacebookPixel';
import FacebookPixels from './FacebookPixel';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.webp" sizes="any" />
        <meta charSet="utf-8" />
        <meta
          name="keywords"
          content="INNO-APAC, technology innovation, investment promotion, entrepreneurship services, incubation operations, talents recruitment,Overseas Talent, APAC region, innovation ecosystem, business consulting, China"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="google-site-verification"
          content="U9XgrZri9t5rKqA88avw_pPntbzG01HKSdJljdiL3cA"
        />
      </head>
      <StoreProvide>
        {' '}
        <body className={inter.className}>
          {' '}
          <Suspense fallback={<Loadingcompante />}>
            <FacebookPixels />
            <ScrollUp />
            {children}
            <Footer />
          </Suspense>
        </body>
      </StoreProvide>
    </html>
  );
}
